### ISSUE TITLE
Add the prefix to links/joints of the URDF

### ISSUE THREAD

**Issue by AndyZe** [motive-ai/moco_ros#5]
PR #4 added a prefix for each robot arm that gets added to the links/joints. It turns out that Motive software requires the joints for all robot arms to have predictable names... so the prefix was not prepended to link/joint names. This should probably be fixed in the future so 2 arms can be used in ROS at once.

ros_control controllers require specific resource names. For example, for a dual-arm robot:

left_joint_J1, right_joint_J1
left_joint_J12, right_joint_J2

**Comment by dvj** [comment]
We have a three-level hierarchy for naming:
Joint Name - the name of the actuator
Chain Name - the name of the kinematic chain
Robot Name - the name of the whole robot

Typically, we've kept the joint name simple (ie: joint_J1), and used the chain name to differentiate parts of the robot (ie: left_arm), and finally an ID for the robot (ie: BOT-12345)

I think we can work with the prefix as long as we use a specific separator (like underscore or period or hyphen) to put them together.

**Comment by AndyZe** [comment]
Closing since the prefix was added back in PR #4
